version: 2

sources:
  - name: sources
    database: alt-school-capstone-project
    schema: airflow-etl
    tables:
      - name: customers
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: product_category_name_translation
      - name: products
      - name: sellers